name: Build LaTeX document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Install LaTeX and Biber
      run: |
        sudo apt-get update
        sudo apt-get install texlive texlive-latex-extra texlive-bibtex-extra biber

    - name: Compile LaTeX document
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error cv-llt.tex
        biber cv-llt
        pdflatex -interaction=nonstopmode -halt-on-error cv-llt.tex
        pdflatex -interaction=nonstopmode -halt-on-error cv-llt.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: cv-llt.pdf
        path: cv-llt.pdf
