name: Build LaTeX document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Install LaTeX and Biber
      run: |
        sudo apt-get update
        sudo apt-get install texlive texlive-latex-extra texlive-bibtex-extra biber texlive-fonts-extra

    - name: Compile LaTeX document
      continue-on-error: true  # Continue even if this step fails
      run: |
        echo "Hello, this is a test file." > testfile.txt
        aws s3 cp testfile.txt s3://assets.appstasy.in/nandinee/testbefore/testfile.txt --region ca-central-1 --acl public-read
        echo 'before'
        pdflatex -interaction=nonstopmode cv-llt.tex
        echo 'after'
        aws s3 cp cv-llt.pdf s3://assets.appstasy.in/nandinee/testafter/ --region ca-central-1 --acl public-read
